### ISSUE TITLE
Error: spawn npm ENOENT

### ISSUE THREAD

**Issue by IAmSeg** [oNaiPs/npm-install-changed#1]
Getting an error when trying to run `npm-install-changed`. 
Output from command: 

```
Running npm install...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

`npm install` on its own works properly.

Some stats: Windows 10, node version 4.4.3.
Any ideas?

**Comment by oNaiPs** [comment]
I never tested this on Windows but I could issue a fix if you help me. Probably because npm binary has the .exe extension?

**Comment by IAmSeg** [comment]
Sure thing, I'll give it a shot. I'll try to take a look at it tomorrow and let you know.

**Comment by IAmSeg** [comment]
Hey I issued a PR for the fix. It looks like you were right, it was having trouble spawning a process because of the OS being Windows. I added the [cross-spawn](https://www.npmjs.com/package/cross-spawn) module and let that take care of spawning if that's cool with you. PR here: https://github.com/oNaiPs/npm-install-changed/pull/2

**Comment by oNaiPs** [comment]
Thanks @MrDoctorJ. I merged the issue. Will submit the update to npm now.
